name: CI for Dev Branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
      - name: Evaluate MLflow Model
        run: |
          pip install mlflow scikit-learn pandas
          python - <<'EOF'
          import mlflow, pandas as pd
          from sklearn.datasets import load_iris
          from sklearn.metrics import accuracy_score
          model = mlflow.pyfunc.load_model("models:/iris_random_forest_model/Production")
          iris = load_iris(as_frame=True)
          X, y = iris.data, iris.target
          preds = model.predict(X)
          acc = accuracy_score(y, preds)
          print("Accuracy:", acc)
          if acc < 0.9:
              raise SystemExit("❌ Accuracy below threshold, failing CI.")
          EOF
